// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieBooking.DAL;

#nullable disable

namespace MovieBooking.DAL.Migrations
{
    [DbContext(typeof(MovieBookingContext))]
    [Migration("20250125015800_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieBooking.BL.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b6bd5d60-ccac-4a20-b2ff-c0decb960409",
                            EmailConfirmed = false,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            ProfilePicture = new byte[0],
                            SecurityStamp = "ca040cca-1a10-4cb1-9d6b-05a95def50df",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f0efe2d7-efe9-42e0-a73b-cb02eb1e91a0",
                            EmailConfirmed = false,
                            FirstName = "Jane",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            ProfilePicture = new byte[0],
                            SecurityStamp = "c397dba5-aa2e-42f4-8796-1c0a6d9e1e84",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "edb240ff-41a8-4efb-8618-22fa42683f81",
                            Email = "alice.smith@example.com",
                            EmailConfirmed = false,
                            FirstName = "Alice",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            ProfilePicture = new byte[0],
                            SecurityStamp = "9d39bfc3-d8b8-48bf-9a3f-ae2d48676fbd",
                            TwoFactorEnabled = false,
                            UserName = "alicesmith"
                        });
                });

            modelBuilder.Entity("MovieBooking.BL.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("MovieId");

                    b.HasIndex("ShowtimeId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 10,
                            ApplicationUserId = "1",
                            BookingDate = new DateTime(2025, 1, 25, 2, 57, 59, 489, DateTimeKind.Local).AddTicks(9822),
                            MovieId = 10,
                            NumberOfSeats = 2,
                            PaymentStatus = "Paid",
                            SeatIds = "1,2",
                            ShowtimeId = 1
                        },
                        new
                        {
                            BookingId = 20,
                            ApplicationUserId = "2",
                            BookingDate = new DateTime(2025, 1, 25, 2, 57, 59, 491, DateTimeKind.Local).AddTicks(9864),
                            MovieId = 20,
                            NumberOfSeats = 1,
                            PaymentStatus = "Pending",
                            SeatIds = "3",
                            ShowtimeId = 2
                        });
                });

            modelBuilder.Entity("MovieBooking.BL.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("MoviePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 10,
                            Description = "A thief who steals corporate secrets through dream-sharing.",
                            Duration = 148,
                            Genre = "Sci-Fi",
                            MoviePicture = new byte[0],
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 20,
                            Description = "Batman battles the Joker in Gotham City.",
                            Duration = 152,
                            Genre = "Action",
                            MoviePicture = new byte[0],
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            MovieId = 30,
                            Description = "A team of explorers travel through a wormhole in space to ensure humanity's survival.",
                            Duration = 169,
                            Genre = "Sci-Fi",
                            MoviePicture = new byte[0],
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Interstellar"
                        },
                        new
                        {
                            MovieId = 40,
                            Description = "The Avengers assemble to reverse the damage caused by Thanos.",
                            Duration = 181,
                            Genre = "Action",
                            MoviePicture = new byte[0],
                            ReleaseDate = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "pulp-fiction"
                        });
                });

            modelBuilder.Entity("MovieBooking.BL.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 20.00m,
                            BookingId = 10,
                            PaymentDate = new DateTime(2025, 1, 25, 2, 57, 59, 492, DateTimeKind.Local).AddTicks(1260),
                            PaymentMethod = "Credit Card"
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 15.00m,
                            BookingId = 20,
                            PaymentDate = new DateTime(2025, 1, 25, 2, 57, 59, 492, DateTimeKind.Local).AddTicks(1737),
                            PaymentMethod = "PayPal"
                        });
                });

            modelBuilder.Entity("MovieBooking.BL.Entities.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<string>("Column")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Row")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("int");

                    b.HasKey("SeatId");

                    b.HasIndex("ShowtimeId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = 100,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 101,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 102,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 103,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 104,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 110,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 111,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 112,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 113,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 114,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 120,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 121,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 122,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 123,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 124,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 130,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 131,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 132,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 133,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 134,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 140,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 141,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 142,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 143,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 144,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 1
                        },
                        new
                        {
                            SeatId = 200,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 201,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 202,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 203,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 204,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 210,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 211,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 212,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 213,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 214,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 220,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 221,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 222,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 223,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 224,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 230,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 231,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 232,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 233,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 234,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 240,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 241,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 242,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 243,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 244,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 2
                        },
                        new
                        {
                            SeatId = 300,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 301,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 302,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 303,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 304,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 310,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 311,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 312,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 313,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 314,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 320,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 321,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 322,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 323,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 324,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 330,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 331,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 332,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 333,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 334,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 340,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 341,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 342,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 343,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 344,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 3
                        },
                        new
                        {
                            SeatId = 400,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 401,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 402,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 403,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 404,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "A",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 410,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 411,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 412,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 413,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 414,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "B",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 420,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 421,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 422,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 423,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 424,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "C",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 430,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 431,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 432,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 433,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 434,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "D",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 440,
                            Column = "1",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 441,
                            Column = "2",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 442,
                            Column = "3",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 443,
                            Column = "4",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        },
                        new
                        {
                            SeatId = 444,
                            Column = "5",
                            IsBooked = false,
                            MovieId = 0,
                            Row = "E",
                            SeatNumber = 0,
                            ShowtimeId = 4
                        });
                });

            modelBuilder.Entity("MovieBooking.BL.Entities.Showtime", b =>
                {
                    b.Property<int>("ShowtimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowtimeId"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ScreenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShowtimeId");

                    b.HasIndex("MovieId");

                    b.ToTable("Showtimes");

                    b.HasData(
                        new
                        {
                            ShowtimeId = 1,
                            AvailableSeats = 10,
                            MovieId = 10,
                            ScreenId = 1,
                            StartTime = new DateTime(2024, 12, 10, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 2,
                            AvailableSeats = 15,
                            MovieId = 20,
                            ScreenId = 1,
                            StartTime = new DateTime(2024, 12, 11, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 3,
                            AvailableSeats = 20,
                            MovieId = 30,
                            ScreenId = 2,
                            StartTime = new DateTime(2024, 12, 12, 21, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 4,
                            AvailableSeats = 25,
                            MovieId = 40,
                            ScreenId = 3,
                            StartTime = new DateTime(2024, 12, 13, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MovieBooking.BL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MovieBooking.BL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBooking.BL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MovieBooking.BL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieBooking.BL.Entities.Booking", b =>
                {
                    b.HasOne("MovieBooking.BL.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("Bookings")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBooking.BL.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBooking.BL.Entities.Showtime", "Showtime")
                        .WithMany("Bookings")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Movie");

                    b.Navigation("Showtime");
                });

            modelBuilder.Entity("MovieBooking.BL.Entities.Payment", b =>
                {
                    b.HasOne("MovieBooking.BL.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("MovieBooking.BL.Entities.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MovieBooking.BL.Entities.Seat", b =>
                {
                    b.HasOne("MovieBooking.BL.Entities.Showtime", "Showtime")
                        .WithMany("Seats")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Showtime");
                });

            modelBuilder.Entity("MovieBooking.BL.Entities.Showtime", b =>
                {
                    b.HasOne("MovieBooking.BL.Entities.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieBooking.BL.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MovieBooking.BL.Entities.Booking", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("MovieBooking.BL.Entities.Movie", b =>
                {
                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("MovieBooking.BL.Entities.Showtime", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
